ACSD-45071 Assignment of sources changes after importing data ACP2E-9…
magento-sparta/inventory-deprecated pull request #165
Opened 2022-08-31 15:21 UTC by fas83501

### Description (*)

Manual Backport based on https://github.com/magento-l3/inventory/pull/106

Backport: ACP2E-982

### Related Pull Request
https://github.com/magento-sparta/magento2ce/pull/1371

2022-09-01 14:33 UTC, robertorubino requested changes

2022-09-01 14:33 UTC, robertorubino commented on InventoryImportExport/etc/di.xml
>          <plugin name="importStockItemDataForSourceItem" type="Magento\InventoryImportExport\Plugin\Import\SourceItemImporter" />
Please check the original PR https://github.com/magento-l3/inventory/pull/106/files#diff-f270f253001fcad91997bf0df71fb7e3d1cba203c9e924459fd68684c7f7cb45L31. This plugin has been removed

2022-09-05 15:05 UTC, robertorubino approved these changes

2022-09-09 19:03 UTC, saddane approved these changes

2022-09-09 19:03 UTC, closed without merging